agents:
  # Custom specialized agents for Gigbook project
  
  otp-architect:
    name: "otp-architect"
    description: "OTP and concurrent systems architect specializing in fault-tolerant Elixir/Erlang applications. Use proactively for designing supervision trees, implementing resilience patterns, optimizing GenServer architectures, handling distributed system challenges, debugging process communication issues, and building scalable concurrent systems."
    tools: ["Read", "Grep", "Glob", "MultiEdit", "Edit", "Write"]
    model: "sonnet"
    color: "purple"
    config_path: ".claude/agents/otp-architect.md"
    
  devops-engineer:
    name: "devops-engineer"  
    description: "Use proactively for fly.io deployment, GitHub Actions CI/CD, infrastructure management, deployment debugging, and production operations. Specialist for Phoenix/Elixir application deployment, release configuration, container optimization, and DevOps best practices."
    tools: ["Read", "Grep", "Glob", "Edit", "MultiEdit", "Write", "Bash", "WebFetch"]
    model: "sonnet"
    color: "orange"
    config_path: ".claude/agents/devops-engineer.md"
    
  devsecops-engineer:
    name: "devsecops-engineer"
    description: "Use proactively for security audits, vulnerability assessments, and implementing security best practices throughout the development lifecycle. Specialist for reviewing authentication, authorization, data protection, dependency security, and compliance requirements."
    tools: ["Read", "Grep", "Glob", "Edit", "MultiEdit", "Bash", "WebFetch"] 
    model: "sonnet"
    color: "red"
    config_path: ".claude/agents/devsecops-engineer.md"
    
  testing-specialist:
    name: "testing-specialist"
    description: "Use proactively for comprehensive testing strategies, test design, and quality assurance in Elixir/Phoenix applications. Specialist for implementing test pyramids, optimizing test suites, debugging flaky tests, and ensuring thorough test coverage. Expert in ExUnit, Mox, Wallaby, and testing best practices."
    tools: ["Read", "Grep", "Glob", "Edit", "MultiEdit", "Bash"]
    model: "sonnet"
    color: "green"
    config_path: ".claude/agents/testing-specialist.md"
    
  ux-designer:
    name: "ux-designer"
    description: "Use proactively for interface improvements, user experience optimization, design system creation, accessibility audits, and user research insights. Specialist for creating consistent, delightful user experiences through thoughtful questioning and evidence-based design decisions. Expert in user research, interaction design, visual design, and accessibility."
    tools: ["Read", "Grep", "Glob", "Edit", "MultiEdit", "Write", "WebFetch"]
    model: "sonnet"
    color: "pink"
    config_path: ".claude/agents/ux-designer.md"

# Agent usage guidelines
guidelines:
  proactive_usage:
    # OTP Architect - Use for:
    - GenServer design and implementation
    - Supervision tree architecture
    - Process communication and registry patterns  
    - Concurrent system design
    - Distributed system challenges
    - Performance optimization for BEAM
    - Fault tolerance and recovery patterns
    
    # DevOps Engineer - Use for:
    - Fly.io deployment configuration and troubleshooting
    - GitHub Actions CI/CD pipeline setup
    - Docker containerization and optimization
    - Infrastructure as code (Terraform, etc.)
    - Production monitoring and alerting
    - Release management and rollback strategies
    - Environment configuration and secrets management
    
    # DevSecOps Engineer - Use for:
    - Security architecture reviews
    - Authentication and authorization implementation
    - Vulnerability assessments and penetration testing
    - Compliance audits (SOC2, GDPR, etc.)
    - Dependency security scanning
    - Data protection and encryption strategies
    - Security incident response planning
    
    # Testing Specialist - Use for:
    - Test strategy and pyramid design
    - Unit test implementation with ExUnit
    - Integration testing with Phoenix
    - End-to-end testing with Wallaby
    - Property-based testing with StreamData
    - Test coverage analysis and improvement
    - Mocking strategies with Mox
    - Performance and load testing
    
    # UX Designer - Use for:
    - User interface design and optimization
    - User experience research and journey mapping
    - Accessibility audits and WCAG compliance
    - Design system creation and maintenance
    - Responsive design implementation
    - User testing and feedback analysis
    - Information architecture improvements
    - Visual design and branding consistency
  
  file_patterns:
    otp-architect:
      - "**/gen_server.ex"
      - "**/supervisor.ex"
      - "**/application.ex"
      - "**/registry.ex"
      - Files containing "GenServer", "Supervisor", "Agent", "Task"
      
    devops-engineer:
      - "fly.toml"
      - "Dockerfile*"
      - ".github/workflows/**"
      - "docker-compose.yml"
      - "**/release.ex"
      - "priv/repo/migrations/**"
      
    devsecops-engineer:
      - "**/auth*.ex"
      - "**/security*.ex"
      - "**/plugs/**"
      - "config/runtime.exs"
      - Files containing authentication, authorization patterns
      
    testing-specialist:
      - "test/**/*.exs"
      - "*_test.exs"
      - "test_helper.exs"
      - Files in test directories
      
    ux-designer:
      - "lib/**/*.eex"
      - "lib/**/*.heex"
      - "assets/**/*.css"
      - "assets/**/*.scss"
      - "priv/static/**"
  
  context_requirements:
    - Always provide relevant project context from CLAUDE.md or README.md
    - Include specific technical requirements and constraints
    - Provide current state information for informed recommendations
    - Share relevant error messages or logs when debugging
    - Include user feedback or metrics when available
    - Specify target environment (dev, staging, production)
    - Remember agents don't have conversation history - be comprehensive
    
  collaboration_patterns:
    # Cross-agent collaboration scenarios
    otp_and_testing:
      - "Use otp-architect for GenServer design, then testing-specialist for comprehensive test coverage"
    
    security_and_devops:
      - "Use devsecops-engineer for security review, then devops-engineer for secure deployment"
      
    ux_and_testing:
      - "Use ux-designer for interface design, then testing-specialist for user acceptance testing"
      
    architecture_and_performance:
      - "Use otp-architect for system design, then devops-engineer for production optimization"
