#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

source ${ZDOTDIR:-$HOME}/.zshenv

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" 
fi


# set up prompt
autoload -Uz promptinit 
promptinit 
prompt matt

# Editorsetup
export EDITOR=nvim

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  # linux config
elif [[ "$OSTYPE" == "darwin"* ]]; then
  # Mac OSX config
  alias vim='nvim'
  alias vi='nvim'
  alias v='nvim' 
fi

# Completions
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

  autoload -Uz compinit
  compinit
fi

